language: node_js
node_js:
  - 14.5.0

jobs:
  include:
    - stage: Test
      script: yarn test
      name: 'Test'
    - name: 'Build & Deploy'
      script: yarn build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        target-branch: master
        local-dir: public
        on:
          branch: develop
